name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract tag name
      run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})"
      id: extract_tag

    - name: Print tag name
      run: echo "Tag Name ${{ steps.extract_tag.outputs.TAG_NAME }}"

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/quantum-quirk:${{ steps.extract_tag.outputs.TAG_NAME }}


